version: 1.0.{build}
install:
- ps: >-
    $url_qt5 = "https://github.com/qt/qt5/archive/v5.11.1.zip"

    Invoke-WebRequest -Uri $url_qt5 -OutFile qt5.zip

    Add-Type -AssemblyName System.IO.Compression.FileSystem

    function Unzip
        {
            param([string]$zipfile, [string]$outpath)
            [System.IO.Compression.ZipFile]::ExtractToDirectory($zipfile, $outpath)
        }

    Unzip "$env:APPVEYOR_BUILD_FOLDER\qt5.zip" "$env:APPVEYOR_BUILD_FOLDER\qt5"
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

    set PATH=%APPVEYOR_BUILD_FOLDER%\qt5\qt5-5.11.1\gnuwin32\bin;%PATH%

    configure -release -static -platform win32-msvc -opensource -confirm-license -nomake examples -nomake tests -nomake tools

    nmake sub-src-qmake_all

    cd src

    nmake sub-corelib

    nmake sub-gui

    nmake sub-widgets

    nmake sub-sql

    nmake sub-plugins
on_failure:
- ps: >-
    $blockRdp = $true;
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
