version: 1.0.{build}
install:
- ps: >-
    $url_qt5 = "https://github.com/qt/qt5/archive/v5.11.1.zip"

    Invoke-WebRequest -Uri $url_qt5 -OutFile qt5.zip

    Add-Type -AssemblyName System.IO.Compression.FileSystem

    function Unzip
        {
            param([string]$zipfile, [string]$outpath)
            [System.IO.Compression.ZipFile]::ExtractToDirectory($zipfile, $outpath)
        }

    Unzip "$env:APPVEYOR_BUILD_FOLDER\qt5.zip" "$env:APPVEYOR_BUILD_FOLDER\qt5"
build_script:
- cmd: >-
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86

    set PATH=%APPVEYOR_BUILD_FOLDER%\qt5\qt5-5.11.1\gnuwin32\bin;%PATH%

    set QT_INSTALL_PATH="C:\Qt\5.11.1\Static-5.11.1"

    configure -prefix %QT_INSTALL_PATH% -release -static -platform win32-msvc -opensource -confirm-license -nomake examples -nomake tests -nomake tools

    nmake sub-src-qmake_all

    nmake sub-qmake-qmake-aux-pro

    cd src

    nmake sub-corelib

    nmake sub-gui

    nmake sub-winmain

    nmake sub-widgets

    nmake sub-sql

    nmake sub-plugins


    nmake sub-corelib-install_subtargets

    nmake sub-gui-install_subtargets

    nmake sub-winmain-install_subtargets

    nmake sub-widgets-install_subtargets

    nmake sub-sql-install_subtargets

    nmake sub-plugins-install_subtargets

    cd ..

    nmake sub-qmake-qmake-aux-pro-install_subtargets

    nmake install_mkspecs

    7z a qtbase-static.zip %QT_INSTALL_PATH%\*
on_failure:
- ps: >-
    $blockRdp = $true;
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
artifacts:
- path: qtbase-static.zip
  name: qtbase-static.zip